# Generated by Django 6.0 on 2025-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
